### ISSUE TITLE
gbtlr模型为什么要对用户特征和item特征做内积和外积呢

### ISSUE THREAD

**Issue by WusamX** [wzhe06/CTRmodel#2]
首先非常感谢将论文和模型整理的这么详细，正在研读中，如题，ctr一般不就是将用户特征向量item特征向量和上下文特征concat后输入模型的吗？

**Comment by wzhe06** [comment]
首先这只是一个toy模型，没有做过多的特征工程的尝试，如果要实际应用的话肯定是需要进行大量特征的尝试和组合的。所以两种方法其实都可以，但很难说哪种方法更好，需要具体问题具体分析。
另外回到这个问题中来，做user和item的inner product和outer product其实是一种特征交叉的方法，而且user embedding是由item embedding产生的，有强相关性，product之后得出的similarity更能体现user的interest。

**Comment by WusamX** [comment]
明白了，是将user和item的交叉特征作为一个新的特征，user和item特征没有再用，还有个小问题，做内积该如何保证user和item的维度呢？谢谢

**Comment by wzhe06** [comment]
这个问题很简单，在构建user embedding的时候就是以item embedding为基础构建的。比如将user点过的广告的item embedding做平均。所以可以说是同源的。
