### ISSUE TITLE
打包完成后找不到class

### ISSUE THREAD

**Issue by niumeng07** [wzhe06/CTRmodel#3]
你好，我用`mvn install`打包完成后，找不到class.
生成的jar文件只有4K，用反编译工具打开后，只有如下目录结果
```
-META-INF
--maven/com.ggstar/CTRmodel
---pom.properties
---pom.xml
--MANIFEST.MF
```
请问这是什么原因，谢谢。

**Comment by wzhe06** [comment]
maven 打包的部分没有实现，如果希望用maven打包的话请自行实现，同时欢迎反馈到项目中来，谢谢。
