### ISSUE TITLE
如何run example function?

### ISSUE THREAD

**Issue by yangcao1989** [wzhe06/CTRmodel#6]
您好，
我是scala spark的新手。刚git clone 下了CTRmodel的source code。我想要run 不同的example function(LR, GBDT, NN etc.)，看到README上面的usage是说"After dependencies are imported by maven automatically, you can simple run the example function"。请问这个具体怎么做？

谢谢

**Comment by wzhe06** [comment]
一般来讲，你最好用idea IDE倒入这个工程，设定为maven project，然后直接执行example function里面的主函数就可以了

**Comment by yangcao1989** [comment]
我下载了IntelliJ IDEA IDE, 并且import了这个project，设为maven project. 然后想run ModelSelection.scala 这个file，遇到一下error msg. 文件23行是spark读取“orc”的data resource,请问这边是读取没有权限吗？

**Exception in thread "main" java.lang.NullPointerException
	at com.ggstar.example.ModelSelection$.main(ModelSelection.scala:23)
	at com.ggstar.example.ModelSelection.main(ModelSelection.scala)**



    val resourcesPath = this.getClass.getResource("/samples.snappy.orc")
    val rawSamples = spark.read.format("orc").option("compression", "snappy").load(resourcesPath.getPath)

**Comment by wzhe06** [comment]
原始的数据文件目前不提供了，抱歉
